### ISSUE TITLE
Broken Discord, Docs, and Support URLs in Dashboard

### ISSUE THREAD

**Issue by sushnag22** [subtrace/subtrace#86]
Hi, just noticed broken URLs for Discord, Docs, and Support routes while trying out Subtrace free trial. Attaching screenshots for reference.

1. Discord
![Screenshot 2024-12-06 002632](https://github.com/user-attachments/assets/f00ae55d-ca31-4527-b100-b111223c8288)

2. Docs
![Screenshot 2024-12-06 002641](https://github.com/user-attachments/assets/451f3256-5060-4550-b5fd-de88556df3c1)

3. Support
![Screenshot 2024-12-06 002646](https://github.com/user-attachments/assets/237c7129-6327-4353-9acf-3dc136b5cb4c)

**Comment by adtac** [comment]
Thanks for catching this! Fixed.
